@startuml

title __STRUCTURAL's Class Diagram__\n

  namespace edu.parinya.softarchdesign.structural {
    class edu.parinya.softarchdesign.structural.Anesthesiologist {
        + Anesthesiologist()
        + service()
    }
  }
  

  namespace edu.parinya.softarchdesign.structural {
    class edu.parinya.softarchdesign.structural.Cardiologist {
        + Cardiologist()
        + service()
    }
  }
  

  namespace edu.parinya.softarchdesign.structural {
    interface edu.parinya.softarchdesign.structural.HealthcareServiceable {
        {abstract} + getPrice()
        {abstract} + service()
    }
  }
  

  namespace edu.parinya.softarchdesign.structural {
    abstract class edu.parinya.softarchdesign.structural.HealthcareWorker {
        - name : String
        - price : double
        + HealthcareWorker()
        + HealthcareWorker()
        + getName()
        + getPrice()
        {abstract} + service()
    }
  }
  

  namespace edu.parinya.softarchdesign.structural {
    class edu.parinya.softarchdesign.structural.HealthcareWorkerDecorator {
        + HealthcareWorkerDecorator()
        + getPrice()
        + service()
    }
  }
  

  namespace edu.parinya.softarchdesign.structural {
    class edu.parinya.softarchdesign.structural.HealthcareWorkerTeam {
        ~ members : ArrayList<HealthcareServiceable>
        + addMember()
        + addMember()
        + getPrice()
        + removeMember()
        + service()
    }
  }
  

  namespace edu.parinya.softarchdesign.structural {
    class edu.parinya.softarchdesign.structural.Main {
        {static} + main()
    }
  }
  

  namespace edu.parinya.softarchdesign.structural {
    class edu.parinya.softarchdesign.structural.Nurse {
        + Nurse()
        + service()
    }
  }
  

  namespace edu.parinya.softarchdesign.structural {
    class edu.parinya.softarchdesign.structural.Surgeon {
        + Surgeon()
        + service()
    }
  }
  

  namespace edu.parinya.softarchdesign.structural {
    class edu.parinya.softarchdesign.structural.TaxPayingHealthcareWorker {
        + TaxPayingHealthcareWorker()
        + getPrice()
    }
  }
  

  namespace edu.parinya.softarchdesign.structural {
    class edu.parinya.softarchdesign.structural.TimeLoggingHealthcareWorker {
        + TimeLoggingHealthcareWorker()
        + service()
    }
  }
  

  edu.parinya.softarchdesign.structural.Anesthesiologist -up-|> edu.parinya.softarchdesign.structural.HealthcareWorker
  edu.parinya.softarchdesign.structural.Cardiologist -up-|> edu.parinya.softarchdesign.structural.HealthcareWorker
  edu.parinya.softarchdesign.structural.HealthcareWorker .up.|> edu.parinya.softarchdesign.structural.HealthcareServiceable
  edu.parinya.softarchdesign.structural.HealthcareWorkerDecorator -up-|> edu.parinya.softarchdesign.structural.HealthcareWorker
  edu.parinya.softarchdesign.structural.HealthcareWorkerDecorator o-- edu.parinya.softarchdesign.structural.HealthcareWorker : tempWorker
  edu.parinya.softarchdesign.structural.HealthcareWorkerTeam .up.|> edu.parinya.softarchdesign.structural.HealthcareServiceable
  edu.parinya.softarchdesign.structural.Nurse -up-|> edu.parinya.softarchdesign.structural.HealthcareWorker
  edu.parinya.softarchdesign.structural.Surgeon -up-|> edu.parinya.softarchdesign.structural.HealthcareWorker
  edu.parinya.softarchdesign.structural.TaxPayingHealthcareWorker -up-|> edu.parinya.softarchdesign.structural.HealthcareWorkerDecorator
  edu.parinya.softarchdesign.structural.TimeLoggingHealthcareWorker -up-|> edu.parinya.softarchdesign.structural.HealthcareWorkerDecorator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
