@startuml

title __LAB8's Class Diagram__\n

  namespace edu.parinya.softarchdesign.structural {
    class edu.parinya.softarchdesign.structural.Anesthesiologist {
    }
  }
  

  namespace edu.parinya.softarchdesign.structural {
    class edu.parinya.softarchdesign.structural.Cardiologist {
    }
  }
  

  namespace edu.parinya.softarchdesign.structural {
    interface edu.parinya.softarchdesign.structural.HealthcareServiceable {
    }
  }
  

  namespace edu.parinya.softarchdesign.structural {
    abstract class edu.parinya.softarchdesign.structural.HealthcareWorker {
    }
  }
  

  namespace edu.parinya.softarchdesign.structural {
    class edu.parinya.softarchdesign.structural.HealthcareWorkerDecorator {
    }
  }
  

  namespace edu.parinya.softarchdesign.structural {
    class edu.parinya.softarchdesign.structural.HealthcareWorkerTeam {
    }
  }
  

  namespace edu.parinya.softarchdesign.structural {
    class edu.parinya.softarchdesign.structural.Main {
    }
  }
  

  namespace edu.parinya.softarchdesign.structural {
    class edu.parinya.softarchdesign.structural.Nurse {
    }
  }
  

  namespace edu.parinya.softarchdesign.structural {
    class edu.parinya.softarchdesign.structural.Surgeon {
    }
  }
  

  namespace edu.parinya.softarchdesign.structural {
    class edu.parinya.softarchdesign.structural.TaxPayingHealthcareWorker {
    }
  }
  

  namespace edu.parinya.softarchdesign.structural {
    class edu.parinya.softarchdesign.structural.TimeLoggingHealthcareWorker {
    }
  }
  

  edu.parinya.softarchdesign.structural.Anesthesiologist -up-|> edu.parinya.softarchdesign.structural.HealthcareWorker
  edu.parinya.softarchdesign.structural.Cardiologist -up-|> edu.parinya.softarchdesign.structural.HealthcareWorker
  edu.parinya.softarchdesign.structural.HealthcareWorker .up.|> edu.parinya.softarchdesign.structural.HealthcareServiceable
  edu.parinya.softarchdesign.structural.HealthcareWorkerDecorator -up-|> edu.parinya.softarchdesign.structural.HealthcareWorker
  edu.parinya.softarchdesign.structural.HealthcareWorkerDecorator o-- edu.parinya.softarchdesign.structural.HealthcareWorker : tempWorker
  edu.parinya.softarchdesign.structural.HealthcareWorkerTeam .up.|> edu.parinya.softarchdesign.structural.HealthcareServiceable
  edu.parinya.softarchdesign.structural.Nurse -up-|> edu.parinya.softarchdesign.structural.HealthcareWorker
  edu.parinya.softarchdesign.structural.Surgeon -up-|> edu.parinya.softarchdesign.structural.HealthcareWorker
  edu.parinya.softarchdesign.structural.TaxPayingHealthcareWorker -up-|> edu.parinya.softarchdesign.structural.HealthcareWorkerDecorator
  edu.parinya.softarchdesign.structural.TimeLoggingHealthcareWorker -up-|> edu.parinya.softarchdesign.structural.HealthcareWorkerDecorator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
